name       : python-pyproj
version    : 3.1.0
release    : 8
source     :
    - https://github.com/pyproj4/pyproj/archive/refs/tags/3.1.0.tar.gz : e12b07b46b72379ee3e76be37d3bedbf6885b85e1f7e526019174df11689e748
license    : ISC
component  : programming.python
summary    : Python interface to PROJ.4 library for cartographic transformations
description: |
    Cython wrapper to provide python interfaces to Proj. Performs cartographic transformations between geographic (Lat/Lon) and map projection (x/y) coordinates. Can also transform directly from one map projection coordinate system to another. Coordinates can be given as numpy arrays, python arrays, lists or scalars. Optimized for numpy arrays.
builddeps  :
    - pkgconfig(proj)
    - pkgconfig(python3)
    - cython
environment: |
    export PROJ_DIR=/usr
setup      : |
    # Remove RPATH
    sed -i "s/runtime_library_dirs=libdirs,//" setup.py
build      : |
    %python3_setup
install    : |
    %python3_install --skip-build
