name       : python-pyproj
version    : 3.4.1
release    : 13
source     :
    - https://github.com/pyproj4/pyproj/archive/refs/tags/3.4.1.tar.gz : 4248cd0c1e0ba8b78600a35ce3c4d6d92a8ef5e9e275dbe843cc22c7bdaa7362
homepage   : https://github.com/pyproj4/pyproj
license    : ISC
component  : programming.python
summary    : Python interface to PROJ.4 library for cartographic transformations
description: |
    Cython wrapper to provide python interfaces to Proj. Performs cartographic transformations between geographic (Lat/Lon) and map projection (x/y) coordinates. Can also transform directly from one map projection coordinate system to another. Coordinates can be given as numpy arrays, python arrays, lists or scalars. Optimized for numpy arrays.
environment: |
    export PROJ_DIR=/usr
builddeps  :
    - pkgconfig(proj)
    - cython
rundeps    :
    - python-certifi
setup      : |
    # Remove RPATH
    sed -i "s/runtime_library_dirs=libdirs,//" setup.py
build      : |
    %python3_setup
install    : |
    %python3_install --skip-build
