name       : python-pyproj
version    : 3.3.0
release    : 11
source     :
    - https://github.com/pyproj4/pyproj/archive/refs/tags/3.3.0.tar.gz : b6994cd82b244f1379a588ddc77e021b9aee4144b485fb5e9457265dd0f8baa1
homepage   : https://github.com/pyproj4/pyproj
license    : ISC
component  : programming.python
summary    : Python interface to PROJ.4 library for cartographic transformations
description: |
    Cython wrapper to provide python interfaces to Proj. Performs cartographic transformations between geographic (Lat/Lon) and map projection (x/y) coordinates. Can also transform directly from one map projection coordinate system to another. Coordinates can be given as numpy arrays, python arrays, lists or scalars. Optimized for numpy arrays.
environment: |
    export PROJ_DIR=/usr
builddeps  :
    - pkgconfig(proj)
    - cython
rundeps    :
    - python-certifi
setup      : |
    # Remove RPATH
    sed -i "s/runtime_library_dirs=libdirs,//" setup.py
build      : |
    %python3_setup
install    : |
    %python3_install --skip-build
